web/homepage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('', include('main.urls')),
  path('admin/', admin.site.urls),  
]

web/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
  path('', views.top, name='top'),
  path('profile', views.profile, name='profile'),
  path('blog', views.blog, name='blog'),
]

web/main/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
  name = models.CharField(max_length=20)
  age = models.IntegerField()


class BlogTag(models.Model):
  name = models.CharField(max_length=15)

  def __str__(self):
    return self.name


class BlogPost(models.Model):
  title = models.CharField(max_length=30)
  created = models.DateField(help_text='作成日')
  tags = models.ManyToManyField(BlogTag, blank=True)
  content = models.TextField()

  def __str__(self):
    return self.title

web/main/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from .models import Profile, BlogPost

# Create your views here.
def top(request):
  return render(request, 'top.html')

def profile(request):
  context = {
    'prof': Profile.objects.first()
  }
  return render(request, 'profile.html', context)

def blog(request):
  context = {
    'blog_list': BlogPost.objects.all(),
  }
  return render(request, 'blog.html', context)

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static css/style.scss %}">
  <title>Luke</title>
</head>
<body>
  <header>
    <div class="header-logo">logo</div>
    <nav>
      <ul>
        <li><a href="{% url 'main:profile' %}">Profile</a></li>
        <li><a href="{% url 'main:blog' %}">Blog</a></li>
      </ul>
    </nav>
  </header>
  {% block body %}
  {% endblock %}
</body>
</html>

web/templates/blog.html
{% extends 'base.html' %}

{% block body %} 
this is blog top page.
{% for blog in blog_list %}
{{blog}}<br>
{{blog.created}}<br>
{% for tag in blog.tags.all %}
{{tag}}<br>
{% endfor %}
{{blog.content}}
{% endfor %}
{% endblock %}

web/templates/profile.html
{% extends 'base.html' %}

{% block body %} 
{{ prof.name }}
{{ prof.age }}
{% endblock %}

web/templates/top.html
{% extends "base.html" %}

{% block body %}
<h1>This is the top page.</h1>
{% endblock %}